apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ledger-ingress-policy
spec:
  podSelector:
    matchLabels:
      app: kairos-ledger
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: kairos-gateway
      ports:
        - protocol: TCP
          port: {{ .Values.ledger.port }}